#
# Fichier de configuration de l'interface Miniduke
#

title = "Fichier de configuration de l'application Miniduke"

[owner]
name = "Minibig"
dob = "2018-02-23T17:00:00+01:00"

# Préferer 127.0.0.1:9200 au lieu de localhost:9200
[elasticsearch]
host = "192.168.0.232:9200"
index = "logstash_test"
type = "mdm"

# Connexion de Logstah à Kafka
# Préferer 127.0.0.1:9092 au lieu de localhost:9092
[kafka]
host = "127.0.0.1:9092"

# Si le launcher est distant, seul launcher.distant sera pris en compte et vis versa
[launcher]
distant_launcher = true

    # Il est conseillé de donner le path absolu
    # Exemple: "/home/root/miniduke/"
    [launcher.distant]
    host = "192.168.0.237"
    user = "root"
    path = "/data/reconia/"

    # Il est conseillé de donner le path absolu
    [launcher.local]
    path = "/Library/WebServer/Documents/miniduke_interface/"

# Pour connection, il est demandé de mettre le système de connexion pour PDO (PHP)
# Si un fichier est requis, il est conseillé de donner le path absolu
# Sinon, partez du dossier "root" de l'interface
[database]
connection = "sqlite:miniduke.db"
type = "sqlite3"
